CREATE TABLE IF NOT EXISTS user(
  id SERIAL,
  email VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  passowrd VARCHAR(255) NOT NULL,
  last_login_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY(id),
  UNIQUE(email)
);

CREATE TABLE keep_list(
  id SERIAL PRIMARY KEY,
  title VARCHAR(127) NOT NULL,
  user_id INTEGER REFERENCES user(id) NOT NULL
);

CREATE table keep(
  id SERIAL PRIMARY KEY,
  NOTE VARCHAR(1000) NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE
  deleted_at TIMESTAMP DEFAULT NULL,
  keep_list_id INTEGER REFERENCES keep_list(id) NOT NULL
);

